export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { About } from "./About";
export { Experience } from "./Experience";
export { Education } from "./Education";
export { Certificates } from "./Certificates";
export { Connect } from "./Connect";
export { Footer } from "./Footer";
export { ThankYou } from "./ThankYou";
