import { AboutDto, ExperienceDto, EducationDto, ToolDto, ProjectDto, CertificationDto } from "./types";

export const about: AboutDto = {
  name: "𝓢𝓱𝓪𝓷𝓴𝓪𝓻 𝓛𝓪𝔁𝓶𝓪𝓷 𝓢𝓪𝓷𝓽𝓲",
  title: "Data Scientist | Full Stack Developer",
  tagline: "Python • Machine Learning • Deep Learning • Generative AI",
  description: [
    "I’m an aspiring **Data Scientist and BCA graduate** passionate about Data Science, Machine Learning, Artificial Intelligence, and Data Analytics.",
    "I work with **Python, SQL, Excel, Power BI, Machine Learning, Data Visualization, and AI** to explore data, uncover patterns, and develop data-driven solutions to real-world problems.",
    "With an additional background in **Full-Stack Development**, I bring both analytical and technical skills to the projects I build. I enjoy learning continuously, solving challenging problems, and transforming ideas and data into practical solutions.",
    "**Currently focused on:** Data Science • Machine Learning • AI • Data Analytics",
  ],
  status: "Available for opportunities",
  images: {
    bannerWebp: "/shankar.jpeg",
    profilePng: "/shankar.png",
    profileWebp: "/Shankar!.jpeg",
  },
  links: {
    website: "https://github.com/shankarsanti",
    email: "shankarsanti2005@gmail.com",
    github: "https://github.com/shankarsanti",
    linkedin: "https://www.linkedin.com/in/shankar-santi/",
    xtwitter: "",
    instagram: "https://www.instagram.com/royal__shankar___/",
    youtube: "",
    phone: "+919035123514",
  },
  connect: [
    "Open to freelance projects and full-time opportunities",
    "Available for consulting and collaboration",
    "Let's build something amazing together!",
  ],
  location: "Athani, Belagavi, Karnataka, India",
};

export const experiences: ExperienceDto[] = [
  {
    title: "Full Stack Developer Intern",
    company: "Nighan2 Labs Pvt. Ltd.",
    url: "https://nighan2.com/",
    period: "September 2025 - April 2026",
    description:
      "Gained hands-on experience building full-stack web applications using React.js, Node.js, Express.js, MongoDB and MySQL. Deployed applications ensuring fast, reliable, and scalable cloud hosting. Collaborated with cross-functional team members using GitHub, creating feature branches, pushing code, and performing pull request reviews and merges. Assisted in cloud deployment and CI/CD workflows to automate build. Contributed to UI/UX improvements and responsive, mobile-first designs using modern front-end best practices.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "MySQL", "Git", "CI/CD"],
    logo: {
      light: "/image.png",
      dark: "/image.png",
    },
  },
  {
    title: "Data Science Trainee",
    company: "Besant Technologies",
    url: "https://www.besanttechnologies.com/branches/besant-technologies-rajaji-nagar-bangalore",
    period: "August 2026 – Present",
    description:
      "Currently pursuing a Data Science course at Besant Technologies, focusing on developing practical skills in data analysis, data visualization, statistics, machine learning, deep learning, and generative AI. Working with Python, SQL, Excel, Power BI, NumPy, Pandas, Matplotlib, and Seaborn to clean, analyze, visualize, and interpret data. Developing practical knowledge of machine learning, deep learning, and Gen AI concepts while working on data-driven projects and real-world problem-solving.",
    technologies: [
      "Python",
      "SQL",
      "Pandas",
      "NumPy",
      "Excel",
      "Power BI",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Deep Learning",
      "Gen AI",
      "AI",
    ],
    logo: {
      light: "/besant-technologies-logo.png",
      dark: "/besant-technologies-logo.png",
    },
  },
];

export const educations: EducationDto[] = [
  {
    course: "Bachelor of Computer Applications (BCA)",
    institution: "Rani Channamma University, Belagavi",
    period: "2023 - 2026",
    description: "Pursuing BCA with focus on full-stack development, data structures, and modern web technologies",
    url: "https://rcub.ac.in",
    logo: {
      light: "",
      dark: "",
    },
    iconName: "FaUniversity",
  },
  {
    course: "Pre-University Course (Science)",
    institution: "Karnataka Secondary Education Examination",
    period: "2021 - 2023",
    description: "Completed PUC with Science stream",
    url: "#",
    logo: {
      light: "",
      dark: "",
    },
    iconName: "FaGraduationCap",
  },
  {
    course: "SSLC",
    institution: "Karnataka Secondary Education Examination Board",
    period: "2021",
    description: "Completed Secondary School Leaving Certificate",
    url: "#",
    logo: {
      light: "",
      dark: "",
    },
    iconName: "FaSchool",
  },
];

export const tools: ToolDto[] = [
  {
    name: "Python",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    },
  },
  {
    name: "ML",
    logo: {
      light: "/icons/ml.svg",
      dark: "/icons/ml.svg",
    },
  },
  {
    name: "DL",
    logo: {
      light: "/icons/dl.svg",
      dark: "/icons/dl.svg",
    },
  },
  {
    name: "Gen AI",
    logo: {
      light: "/icons/genai.svg",
      dark: "/icons/genai.svg",
    },
  },
  {
    name: "Power BI",
    logo: {
      light: "/icons/powerbi.svg",
      dark: "/icons/powerbi.svg",
    },
  },
  {
    name: "Excel",
    logo: {
      light: "/icons/excel.svg",
      dark: "/icons/excel.svg",
    },
  },
  {
    name: "Pandas",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg",
    },
  },
  {
    name: "NumPy",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg",
    },
  },
  {
    name: "MySQL",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    },
  },
  {
    name: "React.js",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    },
  },
  {
    name: "Node.js",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    },
  },
  {
    name: "JavaScript",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    },
  },
  {
    name: "MongoDB",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    },
  },
  {
    name: "Express.js",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
    },
  },
  {
    name: "Django",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
    },
  },
  {
    name: "Tailwind CSS",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
    },
  },
  {
    name: "Git",
    logo: {
      light: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
      dark: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    },
  },
];

export const projects: ProjectDto[] = [
  {
    title: "🛒 E-Commerce Website",
    category: "fullstack",
    featured: true,
    description: "A modern and responsive e-commerce website with product browsing, shopping cart, and a seamless online shopping experience.",
    technologies: ["React", "JavaScript", "HTML", "CSS", "Responsive Design"],
    highlights: [
      "Product catalog browsing & search",
      "Interactive shopping cart & checkout flow",
      "Responsive mobile-first user experience",
      "State management & clean modern UI",
    ],
    github: "https://github.com/shankarsanti/E-Commerce-Website",
    url: "https://e-commerce-website-gamma-tan.vercel.app/",
    image: "/ecommerce-website.png",
  },
  {
    title: "✈️ AI Travel Advisor",
    category: "ai-ml",
    featured: true,
    description: "AI-powered travel assistant for destination discovery, personalized trip planning, recommendations, and day-by-day itinerary generation.",
    technologies: ["React", "Node.js", "Express", "AI", "OpenRouter API"],
    highlights: [
      "AI-Powered destination discovery",
      "Personalized trip planning & recommendations",
      "Day-by-day smart itinerary generation",
      "Integrated with OpenRouter API",
    ],
    github: "https://github.com/shankarsanti/AI-powered-Travel-advisor",
    url: "https://ai-powered-travel-advisor-ten.vercel.app/",
    image: "/ai-travel-advisor.png",
  },
  {
    title: "💊 Pharmacy Management System",
    category: "fullstack",
    featured: true,
    description: "Comprehensive 15-module pharmacy management system with POS/Billing, inventory management, and reporting capabilities.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Tailwind"],
    highlights: [
      "Medicine inventory management",
      "POS billing",
      "Sales tracking",
      "Supplier management",
      "Authentication system",
    ],
    github: "https://github.com/shankarsanti/Pharmacy-Management-System",
    url: "https://pms1.vercel.app/",
    image: "/pharmacy.jpge.png",
  },
  {
    title: "Dairy Management System",
    category: "fullstack",
    featured: true,
    description: "Full-stack ERP web application for dairy management serving 50+ daily users and managing 1,000+ transaction records with real-time MySQL integration.",
    technologies: ["React.js", "HTML5", "CSS3", "MySQL", "Tailwind CSS"],
    highlights: [
      "Designed and developed independently, serving 50+ daily users",
      "Manages 1,000+ transaction records with real-time MySQL integration",
      "Built responsive, mobile-first user interfaces improving cross-device usability by 40%",
      "Implemented secure authentication and role-based access control",
    ],
    github: "https://github.com/shankarsanti/Dairy-management",
    url: "https://dairy-management-lemon.vercel.app/",
    image: "/dairy managmeng.jpge.jpg",
  },
  {
    title: "🎮 Tic-Tac-Toe Game",
    category: "system",
    featured: false,
    description: "A modern browser-based Tic-Tac-Toe game featuring Player vs Player, AI opponent, responsive design, and an interactive gaming experience.",
    technologies: ["HTML5", "CSS3", "JavaScript", "LocalStorage"],
    highlights: [
      "Player vs Player mode",
      "Player vs AI with Smart AI (Minimax algorithm)",
      "Responsive design for all devices",
      "Score tracking with LocalStorage persistence",
      "Dark theme support",
    ],
    github: "https://github.com/shankarsanti/Tic-Tac-Toe-Game",
    url: "https://tic-tac-toe-game-sandy-seven-45.vercel.app/",
    image: "/tic tac toc.png",
  },
  {
    title: "🎓 Student Management System",
    category: "fullstack",
    featured: true,
    description: "A comprehensive web-based platform for managing students, teachers, attendance, exams, fees, and academic performance with role-based access.",
    technologies: ["React", "Node.js", "Express.js", "MongoDB", "Material UI"],
    highlights: [
      "Student & Teacher Management",
      "Attendance Tracking",
      "Exam & Result Management",
      "Fee & Payment System",
      "Dashboard & Reports",
      "Role-Based Authentication",
    ],
    github: "https://github.com/shankarsanti/student-attendance-management-system",
    url: "https://student-attendance-management-syste-xi.vercel.app/",
    image: "/student attendance m.png",
  },
  {
    title: "🚌 Bus Booking System",
    category: "fullstack",
    featured: true,
    description: "A modern online bus booking platform that enables users to search buses, reserve seats, make secure payments, and manage bookings with dedicated Customer, Agent, and Admin dashboards.",
    technologies: ["React", "Vite", "TypeScript", "Firebase", "Tailwind CSS", "Framer Motion"],
    highlights: [
      "Online Bus Search & Booking",
      "Real-Time Seat Selection",
      "Secure Payment Integration",
      "Customer, Agent & Admin Panels",
      "Booking & Ticket Management",
      "Reports & Analytics",
    ],
    github: "https://github.com/shankarsanti/Bus-booking-system",
    url: "https://bus-booking-system-snkr.vercel.app/admin/dashboard",
    image: "/bus booking.png",
  },
  {
    title: "📄 Resume Analyzer",
    category: "ai-ml",
    featured: true,
    description: "An AI-powered web application that analyzes resumes, evaluates ATS compatibility, identifies missing keywords, and provides actionable suggestions to improve job application success.",
    technologies: ["React", "Vite", "TypeScript", "Node.js", "Express.js", "Tailwind CSS"],
    highlights: [
      "AI Resume Analysis",
      "ATS Score Evaluation",
      "Keyword Matching",
      "Job Description Comparison",
      "PDF & DOCX Upload",
      "Improvement Suggestions",
    ],
    github: "https://github.com/shankarsanti/Resume-Analyzer-AI",
    url: "https://resume-analyzer-ai-frontend.vercel.app/",
    image: "/Resume Analyzer.png",
  },
  {
    title: "🌍 Travel Destination Recommendation System",
    category: "ai-ml",
    featured: true,
    description: "An AI-powered travel planning platform that delivers personalized destination recommendations, real-time weather updates, budget planning, and smart itinerary generation for an enhanced travel experience.",
    technologies: ["Python", "Flask", "SQLite", "HTML5", "CSS3", "JavaScript"],
    highlights: [
      "AI Destination Recommendations",
      "Smart Travel Chatbot",
      "Real-Time Weather Forecast",
      "Budget Planner & Cost Calculator",
      "Auto Itinerary Generator",
      "Google Maps Integration",
    ],
    github: "https://github.com/shankarsanti/Travel-Destination-Recommendation-System",
    url: "https://travel-destination-recommendation-s.vercel.app/",
    image: "/travel png.png",
  },
  {
    title: "💼 Online Internship Management System",
    category: "fullstack",
    featured: true,
    description: "A comprehensive web-based platform that streamlines internship management by connecting students, companies, and administrators with application tracking, attendance, performance evaluation, and certificate generation.",
    technologies: ["React", "Node.js", "Express.js", "MySQL", "Tailwind CSS", "Material UI"],
    highlights: [
      "Internship & Application Management",
      "Student, Company & Admin Dashboards",
      "Attendance & Performance Tracking",
      "AI Resume Analyzer",
      "Certificate Generation",
      "Reports & Analytics",
    ],
    github: "https://github.com/shankarsanti/InternHub",
    url: "https://intern-hub-amber.vercel.app/dashboard",
    image: "/intern hub .png",
  },
  {
    title: "🥛 Smart Dairy business",
    category: "system",
    featured: false,
    description: "A modern web-based smart-dairy platform that streamlines farmer management, milk collection, billing, and analytics for efficient dairy operations.",
    technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "PHP", "MySQL"],
    highlights: [
      "Farmer Management",
      "Milk Collection Tracking",
      "Automated Billing System",
      "Fat & SNF Rate Management",
      "Dashboard & Reports",
      "Secure Admin Login",
    ],
    github: "https://github.com/shankarsanti/smart-dairy",
    url: "https://smart-dairy-steel.vercel.app/",
    image: "/smart dairy.png",
  },
];

export const certifications: CertificationDto[] = [
  {
    title: "30 Days Power BI Micro Course",
    issuer: "SkillCourse",
    date: "September 2026",
    description: "Successfully completed comprehensive 30-day Power BI micro course covering data modeling, DAX queries, interactive dashboard design, and business intelligence reporting.",
    credentialUrl: "https://www.skillcourse.in",
    image: "/30 Days Power BI Micro Course.png",
  },
  {
    title: "30 Days Python Micro Course",
    issuer: "SkillCourse",
    date: "September 2026",
    description: "Completed intensive 30-day Python micro course covering core programming fundamentals, data structures, algorithms, object-oriented concepts, and problem-solving.",
    credentialUrl: "https://www.skillcourse.in",
    image: "/30 Days Python Micro Course.png",
  },
  {
    title: "Microsoft Excel Beginners To Advance",
    issuer: "SkillCourse",
    date: "September 2026",
    description: "Completed end-to-end Microsoft Excel course covering formulas, advanced functions, PivotTables, data analysis, visualizations, and automated reporting.",
    credentialUrl: "https://www.skillcourse.in",
    image: "/Microsoft Excel Beginners To Advance.png",
  },
  {
    title: "Data Analytics and AI for Business Leaders",
    issuer: "Nottingham Business School & FutureLearn",
    date: "August 2026",
    description: "Explored data analytics and AI for modern business, covering dashboard interpretation, briefing data teams, navigating ethical challenges, and evidence-based decision making.",
    credentialUrl: "https://www.futurelearn.com/certificates/e65vay4",
    image: "/data-analytics-and-ai-for-business-leaders.png",
  },
  {
    title: "AI For All - AI Appreciate",
    issuer: "Intel & Digital India (CBSE)",
    date: "August 2026",
    description: "Participated in the national AI For All initiative by Intel and Digital India / CBSE, completing the AI Appreciate stage covering AI fundamentals, applications, and ethical implications.",
    image: "/AI FOR ALL certificate.png",
  },
  {
    title: "AI Foundation Course",
    issuer: "AI Classroom (Jio Institute & JioPC)",
    date: "2026",
    description: "Successfully completed the AI Foundation Course by Jio Institute, covering core artificial intelligence concepts, modern AI capabilities, and introductory machine learning principles.",
    image: "/Ai foundation course.jpg",
  },
  {
    title: "Full Stack Development Internship",
    issuer: "Nighan2 Labs Pvt. Ltd.",
    date: "September 2025",
    description: "Completed comprehensive full-stack development internship covering React.js, Node.js, Express.js, MongoDB, and modern web development practices.",
    credentialUrl: "https://nighan2.com/",
    image: "/nighan2labs.com.png",
  },
  {
    title: "Full Stack Development Internship Certificate",
    issuer: "Nighan2 Labs Pvt. Ltd.",
    date: "September 2025",
    description: "Completed comprehensive full-stack development internship covering React.js, Node.js, Express.js, MongoDB, and modern web development practices.",
    credentialUrl: "https://nighan2.com/",
    image: "/internship N2.png",
  },
  {
    title: "CI/CD for Beginners",
    issuer: "Simplilearn SkillUp",
    date: "2026",
    description: "Learn the fundamentals of Continuous Integration and Continuous Deployment (CI/CD), including automated builds, testing, deployment pipelines, and DevOps best practices.",
    image: "/simple learn certificate.png",
  },
  {
    title: "Applied DevOps Engineering with CI/CD",
    issuer: "SeminarRoom Education",
    date: "2026",
    description: "Comprehensive certification covering DevOps fundamentals, CI/CD pipelines, automation, version control, deployment strategies, and modern software delivery practices.",
    image: "/cicd-and-workshop.jpg",
  },
  {
    title: "Front End Development",
    issuer: "SeminarRoom Education",
    date: "2025",
    description: "Comprehensive certification covering HTML, CSS, JavaScript, responsive web design, Bootstrap, UI development, and modern frontend development practices.",
    image: "/front end development.jpg",
  },
  {
    title: "Back End Development",
    issuer: "SeminarRoom Education",
    date: "2025",
    description: "Master backend development fundamentals, server-side programming, databases, APIs, authentication, and real-world web application architecture.",
    image: "/Back End Development and Workshop on.jpg",
  },
  {
    title: "Namaste JavaScript",
    issuer: "Namaste Dev",
    date: "2026",
    description: "Deep dive into JavaScript fundamentals, closures, async programming, and advanced concepts.",
    image: "/Namaste JavaScript.certificate.png",
  },
  {
    title: "IBM Certification",
    issuer: "IBM",
    date: "2026",
    description: "Professional certification in software development and cloud technologies.",
    image: "/IBM certificate .png",
  },
  {
    title: "Workshop on GitHub Copilot",
    issuer: "GitHub",
    date: "2025",
    description: "Hands-on workshop on using GitHub Copilot for AI-assisted coding and productivity enhancement.",
    image: "/github-copilot-workshop.jpeg",
  },
];
